/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class AMsgNoteItemCore extends PItemCore
{
    private PMessageNote _messageNote_;

    public AMsgNoteItemCore()
    {
        // Constructor
    }

    public AMsgNoteItemCore(
        @SuppressWarnings("hiding") PMessageNote _messageNote_)
    {
        // Constructor
        setMessageNote(_messageNote_);

    }

    @Override
    public Object clone()
    {
        return new AMsgNoteItemCore(
            cloneNode(this._messageNote_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMsgNoteItemCore(this);
    }

    public PMessageNote getMessageNote()
    {
        return this._messageNote_;
    }

    public void setMessageNote(PMessageNote node)
    {
        if(this._messageNote_ != null)
        {
            this._messageNote_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._messageNote_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._messageNote_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._messageNote_ == child)
        {
            this._messageNote_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._messageNote_ == oldChild)
        {
            setMessageNote((PMessageNote) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
