/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class AOverPositionPosition extends PPosition
{
    private TOverTok _overTok_;

    public AOverPositionPosition()
    {
        // Constructor
    }

    public AOverPositionPosition(
        @SuppressWarnings("hiding") TOverTok _overTok_)
    {
        // Constructor
        setOverTok(_overTok_);

    }

    @Override
    public Object clone()
    {
        return new AOverPositionPosition(
            cloneNode(this._overTok_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOverPositionPosition(this);
    }

    public TOverTok getOverTok()
    {
        return this._overTok_;
    }

    public void setOverTok(TOverTok node)
    {
        if(this._overTok_ != null)
        {
            this._overTok_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._overTok_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._overTok_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._overTok_ == child)
        {
            this._overTok_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._overTok_ == oldChild)
        {
            setOverTok((TOverTok) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
