/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class APartNoteItemCore extends PItemCore
{
    private PParticipantNote _participantNote_;

    public APartNoteItemCore()
    {
        // Constructor
    }

    public APartNoteItemCore(
        @SuppressWarnings("hiding") PParticipantNote _participantNote_)
    {
        // Constructor
        setParticipantNote(_participantNote_);

    }

    @Override
    public Object clone()
    {
        return new APartNoteItemCore(
            cloneNode(this._participantNote_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPartNoteItemCore(this);
    }

    public PParticipantNote getParticipantNote()
    {
        return this._participantNote_;
    }

    public void setParticipantNote(PParticipantNote node)
    {
        if(this._participantNote_ != null)
        {
            this._participantNote_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._participantNote_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._participantNote_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._participantNote_ == child)
        {
            this._participantNote_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._participantNote_ == oldChild)
        {
            setParticipantNote((PParticipantNote) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
