/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class ARightPositionPosition extends PPosition
{
    private TRightTok _rightTok_;

    public ARightPositionPosition()
    {
        // Constructor
    }

    public ARightPositionPosition(
        @SuppressWarnings("hiding") TRightTok _rightTok_)
    {
        // Constructor
        setRightTok(_rightTok_);

    }

    @Override
    public Object clone()
    {
        return new ARightPositionPosition(
            cloneNode(this._rightTok_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARightPositionPosition(this);
    }

    public TRightTok getRightTok()
    {
        return this._rightTok_;
    }

    public void setRightTok(TRightTok node)
    {
        if(this._rightTok_ != null)
        {
            this._rightTok_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightTok_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rightTok_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rightTok_ == child)
        {
            this._rightTok_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rightTok_ == oldChild)
        {
            setRightTok((TRightTok) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
