/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleStereotype extends PStereotype
{
    private TLDAng _lDAng_;
    private TStereotypeTok _stereotypeTok_;
    private TRDAng _rDAng_;

    public ASimpleStereotype()
    {
        // Constructor
    }

    public ASimpleStereotype(
        @SuppressWarnings("hiding") TLDAng _lDAng_,
        @SuppressWarnings("hiding") TStereotypeTok _stereotypeTok_,
        @SuppressWarnings("hiding") TRDAng _rDAng_)
    {
        // Constructor
        setLDAng(_lDAng_);

        setStereotypeTok(_stereotypeTok_);

        setRDAng(_rDAng_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleStereotype(
            cloneNode(this._lDAng_),
            cloneNode(this._stereotypeTok_),
            cloneNode(this._rDAng_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleStereotype(this);
    }

    public TLDAng getLDAng()
    {
        return this._lDAng_;
    }

    public void setLDAng(TLDAng node)
    {
        if(this._lDAng_ != null)
        {
            this._lDAng_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lDAng_ = node;
    }

    public TStereotypeTok getStereotypeTok()
    {
        return this._stereotypeTok_;
    }

    public void setStereotypeTok(TStereotypeTok node)
    {
        if(this._stereotypeTok_ != null)
        {
            this._stereotypeTok_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stereotypeTok_ = node;
    }

    public TRDAng getRDAng()
    {
        return this._rDAng_;
    }

    public void setRDAng(TRDAng node)
    {
        if(this._rDAng_ != null)
        {
            this._rDAng_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rDAng_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lDAng_)
            + toString(this._stereotypeTok_)
            + toString(this._rDAng_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lDAng_ == child)
        {
            this._lDAng_ = null;
            return;
        }

        if(this._stereotypeTok_ == child)
        {
            this._stereotypeTok_ = null;
            return;
        }

        if(this._rDAng_ == child)
        {
            this._rDAng_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lDAng_ == oldChild)
        {
            setLDAng((TLDAng) newChild);
            return;
        }

        if(this._stereotypeTok_ == oldChild)
        {
            setStereotypeTok((TStereotypeTok) newChild);
            return;
        }

        if(this._rDAng_ == oldChild)
        {
            setRDAng((TRDAng) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
