/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleName extends PName
{
    private TCharSeq _charSeq_;

    public ASimpleName()
    {
        // Constructor
    }

    public ASimpleName(
        @SuppressWarnings("hiding") TCharSeq _charSeq_)
    {
        // Constructor
        setCharSeq(_charSeq_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleName(
            cloneNode(this._charSeq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleName(this);
    }

    public TCharSeq getCharSeq()
    {
        return this._charSeq_;
    }

    public void setCharSeq(TCharSeq node)
    {
        if(this._charSeq_ != null)
        {
            this._charSeq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._charSeq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._charSeq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._charSeq_ == child)
        {
            this._charSeq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._charSeq_ == oldChild)
        {
            setCharSeq((TCharSeq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
