/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import java.util.*;
import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleStartdiagramBlock extends PStartdiagramBlock
{
    private TStartdiagramTok _startdiagramTok_;
    private final LinkedList<TNewLine> _newLine_ = new LinkedList<TNewLine>();

    public ASimpleStartdiagramBlock()
    {
        // Constructor
    }

    public ASimpleStartdiagramBlock(
        @SuppressWarnings("hiding") TStartdiagramTok _startdiagramTok_,
        @SuppressWarnings("hiding") List<?> _newLine_)
    {
        // Constructor
        setStartdiagramTok(_startdiagramTok_);

        setNewLine(_newLine_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleStartdiagramBlock(
            cloneNode(this._startdiagramTok_),
            cloneList(this._newLine_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleStartdiagramBlock(this);
    }

    public TStartdiagramTok getStartdiagramTok()
    {
        return this._startdiagramTok_;
    }

    public void setStartdiagramTok(TStartdiagramTok node)
    {
        if(this._startdiagramTok_ != null)
        {
            this._startdiagramTok_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startdiagramTok_ = node;
    }

    public LinkedList<TNewLine> getNewLine()
    {
        return this._newLine_;
    }

    public void setNewLine(List<?> list)
    {
        for(TNewLine e : this._newLine_)
        {
            e.parent(null);
        }
        this._newLine_.clear();

        for(Object obj_e : list)
        {
            TNewLine e = (TNewLine) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._newLine_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._startdiagramTok_)
            + toString(this._newLine_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._startdiagramTok_ == child)
        {
            this._startdiagramTok_ = null;
            return;
        }

        if(this._newLine_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._startdiagramTok_ == oldChild)
        {
            setStartdiagramTok((TStartdiagramTok) newChild);
            return;
        }

        for(ListIterator<TNewLine> i = this._newLine_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TNewLine) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
