/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class TAliasTok extends Token
{
    public TAliasTok()
    {
        super.setText("as");
    }

    public TAliasTok(int line, int pos)
    {
        super.setText("as");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAliasTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAliasTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAliasTok text.");
    }
}
