/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class TLDAng extends Token
{
    public TLDAng()
    {
        super.setText("<<");
    }

    public TLDAng(int line, int pos)
    {
        super.setText("<<");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLDAng(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLDAng(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLDAng text.");
    }
}
