/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class TOverTok extends Token
{
    public TOverTok()
    {
        super.setText("over");
    }

    public TOverTok(int line, int pos)
    {
        super.setText("over");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOverTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOverTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOverTok text.");
    }
}
