/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class TRightTok extends Token
{
    public TRightTok()
    {
        super.setText("right");
    }

    public TRightTok(int line, int pos)
    {
        super.setText("right");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRightTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRightTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRightTok text.");
    }
}
