/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class TStartdiagramTok extends Token
{
    public TStartdiagramTok()
    {
        super.setText("@startuml");
    }

    public TStartdiagramTok(int line, int pos)
    {
        super.setText("@startuml");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStartdiagramTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStartdiagramTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStartdiagramTok text.");
    }
}
