/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.node;

import plantuml.analysis.*;

@SuppressWarnings("nls")
public final class TStereotypeTok extends Token
{
    public TStereotypeTok()
    {
        super.setText("Participant");
    }

    public TStereotypeTok(int line, int pos)
    {
        super.setText("Participant");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStereotypeTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStereotypeTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStereotypeTok text.");
    }
}
