/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class AConditionDataCondition extends PDataCondition
{
    private PConditionClause _conditionClause_;

    public AConditionDataCondition()
    {
        // Constructor
    }

    public AConditionDataCondition(
        @SuppressWarnings("hiding") PConditionClause _conditionClause_)
    {
        // Constructor
        setConditionClause(_conditionClause_);

    }

    @Override
    public Object clone()
    {
        return new AConditionDataCondition(
            cloneNode(this._conditionClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConditionDataCondition(this);
    }

    public PConditionClause getConditionClause()
    {
        return this._conditionClause_;
    }

    public void setConditionClause(PConditionClause node)
    {
        if(this._conditionClause_ != null)
        {
            this._conditionClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionClause_ == child)
        {
            this._conditionClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionClause_ == oldChild)
        {
            setConditionClause((PConditionClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
