/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class ADataDataCondition extends PDataCondition
{
    private PDataClause _dataClause_;

    public ADataDataCondition()
    {
        // Constructor
    }

    public ADataDataCondition(
        @SuppressWarnings("hiding") PDataClause _dataClause_)
    {
        // Constructor
        setDataClause(_dataClause_);

    }

    @Override
    public Object clone()
    {
        return new ADataDataCondition(
            cloneNode(this._dataClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADataDataCondition(this);
    }

    public PDataClause getDataClause()
    {
        return this._dataClause_;
    }

    public void setDataClause(PDataClause node)
    {
        if(this._dataClause_ != null)
        {
            this._dataClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dataClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dataClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dataClause_ == child)
        {
            this._dataClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dataClause_ == oldChild)
        {
            setDataClause((PDataClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
