/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class AFreshFunction extends PFunction
{
    private PFreshClause _freshClause_;

    public AFreshFunction()
    {
        // Constructor
    }

    public AFreshFunction(
        @SuppressWarnings("hiding") PFreshClause _freshClause_)
    {
        // Constructor
        setFreshClause(_freshClause_);

    }

    @Override
    public Object clone()
    {
        return new AFreshFunction(
            cloneNode(this._freshClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFreshFunction(this);
    }

    public PFreshClause getFreshClause()
    {
        return this._freshClause_;
    }

    public void setFreshClause(PFreshClause node)
    {
        if(this._freshClause_ != null)
        {
            this._freshClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._freshClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._freshClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._freshClause_ == child)
        {
            this._freshClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._freshClause_ == oldChild)
        {
            setFreshClause((PFreshClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
