/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class ASecretConditionClause extends PConditionClause
{
    private PSecretClause _secretClause_;

    public ASecretConditionClause()
    {
        // Constructor
    }

    public ASecretConditionClause(
        @SuppressWarnings("hiding") PSecretClause _secretClause_)
    {
        // Constructor
        setSecretClause(_secretClause_);

    }

    @Override
    public Object clone()
    {
        return new ASecretConditionClause(
            cloneNode(this._secretClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASecretConditionClause(this);
    }

    public PSecretClause getSecretClause()
    {
        return this._secretClause_;
    }

    public void setSecretClause(PSecretClause node)
    {
        if(this._secretClause_ != null)
        {
            this._secretClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._secretClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._secretClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._secretClause_ == child)
        {
            this._secretClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._secretClause_ == oldChild)
        {
            setSecretClause((PSecretClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
