/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class ASignatureFunction extends PFunction
{
    private PSignatureClause _signatureClause_;

    public ASignatureFunction()
    {
        // Constructor
    }

    public ASignatureFunction(
        @SuppressWarnings("hiding") PSignatureClause _signatureClause_)
    {
        // Constructor
        setSignatureClause(_signatureClause_);

    }

    @Override
    public Object clone()
    {
        return new ASignatureFunction(
            cloneNode(this._signatureClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASignatureFunction(this);
    }

    public PSignatureClause getSignatureClause()
    {
        return this._signatureClause_;
    }

    public void setSignatureClause(PSignatureClause node)
    {
        if(this._signatureClause_ != null)
        {
            this._signatureClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._signatureClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._signatureClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._signatureClause_ == child)
        {
            this._signatureClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._signatureClause_ == oldChild)
        {
            setSignatureClause((PSignatureClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
