/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleDataClause extends PDataClause
{
    private PDataExpression _dataExpression_;

    public ASimpleDataClause()
    {
        // Constructor
    }

    public ASimpleDataClause(
        @SuppressWarnings("hiding") PDataExpression _dataExpression_)
    {
        // Constructor
        setDataExpression(_dataExpression_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleDataClause(
            cloneNode(this._dataExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleDataClause(this);
    }

    public PDataExpression getDataExpression()
    {
        return this._dataExpression_;
    }

    public void setDataExpression(PDataExpression node)
    {
        if(this._dataExpression_ != null)
        {
            this._dataExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dataExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dataExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dataExpression_ == child)
        {
            this._dataExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dataExpression_ == oldChild)
        {
            setDataExpression((PDataExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
