/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class TFreshTok extends Token
{
    public TFreshTok()
    {
        super.setText("fresh");
    }

    public TFreshTok(int line, int pos)
    {
        super.setText("fresh");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFreshTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFreshTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFreshTok text.");
    }
}
