/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class THashTok extends Token
{
    public THashTok()
    {
        super.setText("hash");
    }

    public THashTok(int line, int pos)
    {
        super.setText("hash");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THashTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHashTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THashTok text.");
    }
}
