/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class TIdTok extends Token
{
    public TIdTok()
    {
        super.setText("id");
    }

    public TIdTok(int line, int pos)
    {
        super.setText("id");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIdTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIdTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIdTok text.");
    }
}
