/* This file was generated by SableCC (http://www.sablecc.org/). */

package protocol.node;

import protocol.analysis.*;

@SuppressWarnings("nls")
public final class TWeakauthTok extends Token
{
    public TWeakauthTok()
    {
        super.setText("weakauthentication");
    }

    public TWeakauthTok(int line, int pos)
    {
        super.setText("weakauthentication");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TWeakauthTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWeakauthTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TWeakauthTok text.");
    }
}
