/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.analysis;

import plantuml.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseASimpleBcseqdiag(ASimpleBcseqdiag node);
    void caseASimpleStartdiagramBlock(ASimpleStartdiagramBlock node);
    void caseASimpleEnddiagramBlock(ASimpleEnddiagramBlock node);
    void caseASimpleItem(ASimpleItem node);
    void caseAPartItemCore(APartItemCore node);
    void caseAPartNoteItemCore(APartNoteItemCore node);
    void caseAMsgItemCore(AMsgItemCore node);
    void caseAMsgNoteItemCore(AMsgNoteItemCore node);
    void caseAMsgNoteLinkItemCore(AMsgNoteLinkItemCore node);
    void caseASimpleParticipant(ASimpleParticipant node);
    void caseASimpleParticipantName(ASimpleParticipantName node);
    void caseASimplePartAlias(ASimplePartAlias node);
    void caseASimplePartAliasName(ASimplePartAliasName node);
    void caseASimpleStereotype(ASimpleStereotype node);
    void caseASimpleParticipantNote(ASimpleParticipantNote node);
    void caseASimpleParticipantRef(ASimpleParticipantRef node);
    void caseALeftPositionPosition(ALeftPositionPosition node);
    void caseAOverPositionPosition(AOverPositionPosition node);
    void caseARightPositionPosition(ARightPositionPosition node);
    void caseASimpleMessage(ASimpleMessage node);
    void caseASimpleSender(ASimpleSender node);
    void caseASimpleReceiver(ASimpleReceiver node);
    void caseASimpleMessageNote(ASimpleMessageNote node);
    void caseASimpleAliasNoteBlock(ASimpleAliasNoteBlock node);
    void caseASimpleAliasNote(ASimpleAliasNote node);
    void caseASimpleMessageName(ASimpleMessageName node);
    void caseASimpleMessageRef(ASimpleMessageRef node);
    void caseASimpleMsgnoteLink(ASimpleMsgnoteLink node);
    void caseASimpleContent(ASimpleContent node);
    void caseASimpleNoteRef(ASimpleNoteRef node);
    void caseASimpleName(ASimpleName node);

    void caseTColon(TColon node);
    void caseTArrow(TArrow node);
    void caseTLDAng(TLDAng node);
    void caseTRDAng(TRDAng node);
    void caseTNoteMsgAng(TNoteMsgAng node);
    void caseTMsgLink(TMsgLink node);
    void caseTQuot(TQuot node);
    void caseTSlash(TSlash node);
    void caseTStartdiagramTok(TStartdiagramTok node);
    void caseTEnddiagramTok(TEnddiagramTok node);
    void caseTParticipantTok(TParticipantTok node);
    void caseTStereotypeTok(TStereotypeTok node);
    void caseTAliasTok(TAliasTok node);
    void caseTNoteTok(TNoteTok node);
    void caseTLeftTok(TLeftTok node);
    void caseTRightTok(TRightTok node);
    void caseTOverTok(TOverTok node);
    void caseTEndTok(TEndTok node);
    void caseTCharSeq(TCharSeq node);
    void caseTOpaqueexpr(TOpaqueexpr node);
    void caseTIgn(TIgn node);
    void caseTNewLine(TNewLine node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
