/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class AInputStereotype extends PStereotype
{
    private PInputassetSt _inputassetSt_;

    public AInputStereotype()
    {
        // Constructor
    }

    public AInputStereotype(
        @SuppressWarnings("hiding") PInputassetSt _inputassetSt_)
    {
        // Constructor
        setInputassetSt(_inputassetSt_);

    }

    @Override
    public Object clone()
    {
        return new AInputStereotype(
            cloneNode(this._inputassetSt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInputStereotype(this);
    }

    public PInputassetSt getInputassetSt()
    {
        return this._inputassetSt_;
    }

    public void setInputassetSt(PInputassetSt node)
    {
        if(this._inputassetSt_ != null)
        {
            this._inputassetSt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inputassetSt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inputassetSt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inputassetSt_ == child)
        {
            this._inputassetSt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inputassetSt_ == oldChild)
        {
            setInputassetSt((PInputassetSt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
