/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleInassetsList extends PInassetsList
{
    private PInputAssetName _inputAssetName_;

    public ASimpleInassetsList()
    {
        // Constructor
    }

    public ASimpleInassetsList(
        @SuppressWarnings("hiding") PInputAssetName _inputAssetName_)
    {
        // Constructor
        setInputAssetName(_inputAssetName_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleInassetsList(
            cloneNode(this._inputAssetName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleInassetsList(this);
    }

    public PInputAssetName getInputAssetName()
    {
        return this._inputAssetName_;
    }

    public void setInputAssetName(PInputAssetName node)
    {
        if(this._inputAssetName_ != null)
        {
            this._inputAssetName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inputAssetName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inputAssetName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inputAssetName_ == child)
        {
            this._inputAssetName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inputAssetName_ == oldChild)
        {
            setInputAssetName((PInputAssetName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
