/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleOutassetsList extends POutassetsList
{
    private POutputAssetName _outputAssetName_;

    public ASimpleOutassetsList()
    {
        // Constructor
    }

    public ASimpleOutassetsList(
        @SuppressWarnings("hiding") POutputAssetName _outputAssetName_)
    {
        // Constructor
        setOutputAssetName(_outputAssetName_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleOutassetsList(
            cloneNode(this._outputAssetName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleOutassetsList(this);
    }

    public POutputAssetName getOutputAssetName()
    {
        return this._outputAssetName_;
    }

    public void setOutputAssetName(POutputAssetName node)
    {
        if(this._outputAssetName_ != null)
        {
            this._outputAssetName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._outputAssetName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._outputAssetName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._outputAssetName_ == child)
        {
            this._outputAssetName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._outputAssetName_ == oldChild)
        {
            setOutputAssetName((POutputAssetName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
