/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleTransactionList extends PTransactionList
{
    private PTransaction _transaction_;

    public ASimpleTransactionList()
    {
        // Constructor
    }

    public ASimpleTransactionList(
        @SuppressWarnings("hiding") PTransaction _transaction_)
    {
        // Constructor
        setTransaction(_transaction_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleTransactionList(
            cloneNode(this._transaction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleTransactionList(this);
    }

    public PTransaction getTransaction()
    {
        return this._transaction_;
    }

    public void setTransaction(PTransaction node)
    {
        if(this._transaction_ != null)
        {
            this._transaction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._transaction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._transaction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._transaction_ == child)
        {
            this._transaction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._transaction_ == oldChild)
        {
            setTransaction((PTransaction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
