/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleParticipantSt extends PParticipantSt
{
    private TParticipantStereotype _participantStereotype_;
    private PTransactions _transactions_;

    public ASimpleParticipantSt()
    {
        // Constructor
    }

    public ASimpleParticipantSt(
        @SuppressWarnings("hiding") TParticipantStereotype _participantStereotype_,
        @SuppressWarnings("hiding") PTransactions _transactions_)
    {
        // Constructor
        setParticipantStereotype(_participantStereotype_);

        setTransactions(_transactions_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleParticipantSt(
            cloneNode(this._participantStereotype_),
            cloneNode(this._transactions_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleParticipantSt(this);
    }

    public TParticipantStereotype getParticipantStereotype()
    {
        return this._participantStereotype_;
    }

    public void setParticipantStereotype(TParticipantStereotype node)
    {
        if(this._participantStereotype_ != null)
        {
            this._participantStereotype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._participantStereotype_ = node;
    }

    public PTransactions getTransactions()
    {
        return this._transactions_;
    }

    public void setTransactions(PTransactions node)
    {
        if(this._transactions_ != null)
        {
            this._transactions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._transactions_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._participantStereotype_)
            + toString(this._transactions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._participantStereotype_ == child)
        {
            this._participantStereotype_ = null;
            return;
        }

        if(this._transactions_ == child)
        {
            this._transactions_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._participantStereotype_ == oldChild)
        {
            setParticipantStereotype((TParticipantStereotype) newChild);
            return;
        }

        if(this._transactions_ == oldChild)
        {
            setTransactions((PTransactions) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
