/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class TConditionTaggedtok extends Token
{
    public TConditionTaggedtok()
    {
        super.setText("condition");
    }

    public TConditionTaggedtok(int line, int pos)
    {
        super.setText("condition");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TConditionTaggedtok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConditionTaggedtok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TConditionTaggedtok text.");
    }
}
