/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class TConfidentialTok extends Token
{
    public TConfidentialTok()
    {
        super.setText("confidential");
    }

    public TConfidentialTok(int line, int pos)
    {
        super.setText("confidential");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TConfidentialTok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConfidentialTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TConfidentialTok text.");
    }
}
