/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class TDataTaggedtok extends Token
{
    public TDataTaggedtok()
    {
        super.setText("data");
    }

    public TDataTaggedtok(int line, int pos)
    {
        super.setText("data");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDataTaggedtok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDataTaggedtok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDataTaggedtok text.");
    }
}
