/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class TDigitalsignatureTaggedtok extends Token
{
    public TDigitalsignatureTaggedtok()
    {
        super.setText("digitalSignature");
    }

    public TDigitalsignatureTaggedtok(int line, int pos)
    {
        super.setText("digitalSignature");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDigitalsignatureTaggedtok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDigitalsignatureTaggedtok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDigitalsignatureTaggedtok text.");
    }
}
