/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class TInputassetsTaggedtok extends Token
{
    public TInputassetsTaggedtok()
    {
        super.setText("inputAssets");
    }

    public TInputassetsTaggedtok(int line, int pos)
    {
        super.setText("inputAssets");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInputassetsTaggedtok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInputassetsTaggedtok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInputassetsTaggedtok text.");
    }
}
