/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class TReceiverTaggedtok extends Token
{
    public TReceiverTaggedtok()
    {
        super.setText("receiverAddress");
    }

    public TReceiverTaggedtok(int line, int pos)
    {
        super.setText("receiverAddress");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReceiverTaggedtok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReceiverTaggedtok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReceiverTaggedtok text.");
    }
}
