/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.node;

import approfile.analysis.*;

@SuppressWarnings("nls")
public final class TSenderpubkeyTaggedtok extends Token
{
    public TSenderpubkeyTaggedtok()
    {
        super.setText("senderPubKey");
    }

    public TSenderpubkeyTaggedtok(int line, int pos)
    {
        super.setText("senderPubKey");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSenderpubkeyTaggedtok(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSenderpubkeyTaggedtok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSenderpubkeyTaggedtok text.");
    }
}
