/* This file was generated by SableCC (http://www.sablecc.org/). */

package approfile.lexer;

import java.io.*;
import approfile.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEquals(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOpenRound(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCloseRound(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOpenCurly(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCloseCurly(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParticipantStereotype(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInputassetStereotype(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOutputassetStereotype(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdTaggedtok(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenderpubkeyTaggedtok(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenderaddressTaggedtok(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDigitalsignatureTaggedtok(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTransactionTaggedtok(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInputassetsTaggedtok(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOutputassetsTaggedtok(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDataTaggedtok(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReceiverTaggedtok(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProvenanceTaggedtok(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConditionTaggedtok(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFreshTok(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAuthenticTok(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConfidentialTok(line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCharSeq(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOpaqueexpr(text, line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgn(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNewLine(text, line, pos); }
    Token new27(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{10, 10, 1}, {13, 13, 2}, {32, 32, 3}, {40, 40, 4}, {41, 41, 5}, {44, 44, 6}, {45, 45, 7}, {48, 57, 8}, {58, 58, 9}, {60, 60, 10}, {61, 61, 11}, {65, 90, 12}, {91, 91, 13}, {95, 95, 14}, {97, 97, 15}, {98, 98, 16}, {99, 99, 17}, {100, 100, 18}, {101, 101, 16}, {102, 102, 19}, {103, 104, 16}, {105, 105, 20}, {106, 110, 16}, {111, 111, 21}, {112, 112, 22}, {113, 113, 16}, {114, 114, 23}, {115, 115, 24}, {116, 116, 25}, {117, 122, 16}, {123, 123, 26}, {125, 125, 27}, },
            {},
            {{10, 10, 28}, },
            {{32, 32, 3}, },
            {},
            {},
            {},
            {{45, 45, 29}, {48, 57, 30}, {58, 58, 31}, {65, 90, 32}, {95, 95, 33}, {97, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 122, -9}, },
            {{60, 60, 35}, },
            {},
            {{45, 122, -9}, },
            {{0, 35, 36}, {37, 90, 36}, {92, 92, 36}, {93, 93, 37}, {94, 65535, 36}, },
            {{45, 122, -9}, },
            {{45, 95, -9}, {97, 116, 34}, {117, 117, 38}, {118, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 95, -9}, {97, 110, 34}, {111, 111, 39}, {112, 122, 34}, },
            {{45, 95, -9}, {97, 97, 40}, {98, 104, 34}, {105, 105, 41}, {106, 122, 34}, },
            {{45, 95, -9}, {97, 113, 34}, {114, 114, 42}, {115, 122, 34}, },
            {{45, 95, -9}, {97, 99, 34}, {100, 100, 43}, {101, 109, 34}, {110, 110, 44}, {111, 122, 34}, },
            {{45, 116, -17}, {117, 117, 45}, {118, 122, 34}, },
            {{45, 113, -21}, {114, 114, 46}, {115, 122, 34}, },
            {{45, 95, -9}, {97, 100, 34}, {101, 101, 47}, {102, 122, 34}, },
            {{45, 100, -25}, {101, 101, 48}, {102, 122, 34}, },
            {{45, 113, -21}, {114, 114, 49}, {115, 122, 34}, },
            {},
            {},
            {},
            {{45, 122, -9}, },
            {{45, 122, -9}, },
            {{45, 122, -9}, },
            {{45, 122, -9}, },
            {{45, 122, -9}, },
            {{45, 122, -9}, },
            {{73, 73, 50}, {79, 79, 51}, {80, 80, 52}, },
            {{0, 65535, -15}, },
            {},
            {{45, 95, -9}, {97, 115, 34}, {116, 116, 53}, {117, 122, 34}, },
            {{45, 95, -9}, {97, 109, 34}, {110, 110, 54}, {111, 122, 34}, },
            {{45, 115, -40}, {116, 116, 55}, {117, 122, 34}, },
            {{45, 95, -9}, {97, 102, 34}, {103, 103, 56}, {104, 122, 34}, },
            {{45, 100, -25}, {101, 101, 57}, {102, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 95, -9}, {97, 111, 34}, {112, 112, 58}, {113, 122, 34}, },
            {{45, 115, -40}, {116, 116, 59}, {117, 122, 34}, },
            {{45, 110, -19}, {111, 111, 60}, {112, 122, 34}, },
            {{45, 95, -9}, {97, 98, 34}, {99, 99, 61}, {100, 122, 34}, },
            {{45, 109, -41}, {110, 110, 62}, {111, 122, 34}, },
            {{45, 95, -9}, {97, 97, 63}, {98, 122, 34}, },
            {{110, 110, 64}, },
            {{117, 117, 65}, },
            {{97, 97, 66}, },
            {{45, 95, -9}, {97, 103, 34}, {104, 104, 67}, {105, 122, 34}, },
            {{45, 99, -22}, {100, 100, 68}, {101, 101, 34}, {102, 102, 69}, {103, 122, 34}, },
            {{45, 95, -9}, {97, 97, 70}, {98, 122, 34}, },
            {{45, 95, -9}, {97, 104, 34}, {105, 105, 71}, {106, 122, 34}, },
            {{45, 95, -9}, {97, 114, 34}, {115, 115, 72}, {116, 122, 34}, },
            {{45, 116, -17}, {117, 117, 73}, {118, 122, 34}, },
            {{45, 111, -46}, {112, 112, 74}, {113, 122, 34}, },
            {{45, 95, -9}, {97, 117, 34}, {118, 118, 75}, {119, 122, 34}, },
            {{45, 100, -25}, {101, 101, 76}, {102, 122, 34}, },
            {{45, 99, -22}, {100, 100, 77}, {101, 122, 34}, },
            {{45, 109, -41}, {110, 110, 78}, {111, 122, 34}, },
            {{112, 112, 79}, },
            {{116, 116, 80}, },
            {{114, 114, 81}, },
            {{45, 100, -25}, {101, 101, 82}, {102, 122, 34}, },
            {{45, 104, -58}, {105, 105, 83}, {106, 122, 34}, },
            {{45, 104, -58}, {105, 105, 84}, {106, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 115, -40}, {116, 116, 85}, {117, 122, 34}, },
            {{45, 103, -55}, {104, 104, 86}, {105, 122, 34}, },
            {{45, 115, -40}, {116, 116, 87}, {117, 122, 34}, },
            {{45, 116, -17}, {117, 117, 88}, {118, 122, 34}, },
            {{45, 100, -25}, {101, 101, 89}, {102, 122, 34}, },
            {{45, 104, -58}, {105, 105, 90}, {106, 122, 34}, },
            {{45, 100, -25}, {101, 101, 91}, {102, 122, 34}, },
            {{45, 114, -59}, {115, 115, 92}, {116, 122, 34}, },
            {{117, 117, 93}, },
            {{112, 112, 94}, },
            {{116, 116, 95}, },
            {{45, 109, -41}, {110, 110, 96}, {111, 122, 34}, },
            {{45, 115, -40}, {116, 116, 97}, {117, 122, 34}, },
            {{45, 99, -22}, {100, 100, 98}, {101, 122, 34}, },
            {{45, 95, -9}, {97, 97, 99}, {98, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 58, -9}, {65, 65, 100}, {66, 90, 32}, {95, 122, -9}, },
            {{45, 115, -40}, {116, 116, 101}, {117, 122, 34}, },
            {{45, 109, -41}, {110, 110, 102}, {111, 122, 34}, },
            {{45, 117, -62}, {118, 118, 103}, {119, 122, 34}, },
            {{45, 113, -21}, {114, 114, 104}, {115, 122, 34}, },
            {{45, 95, -9}, {97, 97, 105}, {98, 122, 34}, },
            {{116, 116, 106}, },
            {{117, 117, 107}, },
            {{105, 105, 108}, },
            {{45, 115, -40}, {116, 116, 109}, {117, 122, 34}, },
            {{45, 104, -58}, {105, 105, 110}, {106, 122, 34}, },
            {{45, 100, -25}, {101, 101, 111}, {102, 122, 34}, },
            {{45, 95, -9}, {97, 107, 34}, {108, 108, 112}, {109, 122, 34}, },
            {{45, 114, -59}, {115, 115, 113}, {116, 122, 34}, },
            {{45, 58, -9}, {65, 65, 114}, {66, 122, -89}, },
            {{45, 95, -9}, {97, 97, 115}, {98, 122, 34}, },
            {{45, 100, -25}, {101, 101, 116}, {102, 122, 34}, },
            {{45, 58, -9}, {65, 65, 117}, {66, 79, 32}, {80, 80, 118}, {81, 90, 32}, {95, 122, -9}, },
            {{45, 98, -49}, {99, 99, 119}, {100, 122, 34}, },
            {{65, 65, 120}, },
            {{116, 116, 121}, },
            {{99, 99, 122}, },
            {{45, 104, -58}, {105, 105, 123}, {106, 122, 34}, },
            {{45, 110, -19}, {111, 111, 124}, {112, 122, 34}, },
            {{45, 109, -41}, {110, 110, 125}, {111, 122, 34}, },
            {{45, 58, -9}, {65, 82, 32}, {83, 83, 126}, {84, 90, 32}, {95, 122, -9}, },
            {{45, 114, -59}, {115, 115, 127}, {116, 122, 34}, },
            {{45, 114, -59}, {115, 115, 128}, {116, 122, 34}, },
            {{45, 109, -41}, {110, 110, 129}, {111, 122, 34}, },
            {{45, 113, -21}, {114, 114, 130}, {115, 122, 34}, },
            {{45, 99, -22}, {100, 100, 131}, {101, 122, 34}, },
            {{45, 116, -17}, {117, 117, 132}, {118, 122, 34}, },
            {{45, 115, -40}, {116, 116, 133}, {117, 122, 34}, },
            {{115, 115, 134}, },
            {{65, 65, 135}, },
            {{105, 105, 136}, },
            {{45, 98, -49}, {99, 99, 137}, {100, 122, 34}, },
            {{45, 109, -41}, {110, 110, 138}, {111, 122, 34}, },
            {{45, 115, -40}, {116, 116, 139}, {117, 122, 34}, },
            {{45, 104, -58}, {105, 105, 140}, {106, 122, 34}, },
            {{45, 100, -25}, {101, 101, 141}, {102, 122, 34}, },
            {{45, 114, -59}, {115, 115, 142}, {116, 122, 34}, },
            {{45, 98, -49}, {99, 99, 143}, {100, 122, 34}, },
            {{45, 58, -9}, {65, 65, 144}, {66, 122, -89}, },
            {{45, 99, -22}, {100, 100, 145}, {101, 122, 34}, },
            {{45, 95, -9}, {97, 97, 34}, {98, 98, 146}, {99, 122, 34}, },
            {{45, 104, -58}, {105, 105, 147}, {106, 122, 34}, },
            {{115, 115, 148}, },
            {{115, 115, 149}, },
            {{112, 112, 150}, },
            {{45, 122, -9}, },
            {{45, 122, -9}, },
            {{45, 104, -58}, {105, 105, 151}, {106, 122, 34}, },
            {{45, 102, -43}, {103, 103, 152}, {104, 122, 34}, },
            {{45, 115, -40}, {116, 116, 153}, {117, 122, 34}, },
            {{45, 100, -25}, {101, 101, 154}, {102, 122, 34}, },
            {{45, 100, -25}, {101, 101, 155}, {102, 122, 34}, },
            {{45, 99, -22}, {100, 100, 156}, {101, 122, 34}, },
            {{45, 113, -21}, {114, 114, 157}, {115, 122, 34}, },
            {{45, 58, -9}, {65, 74, 32}, {75, 75, 158}, {76, 90, 32}, {95, 122, -9}, },
            {{45, 110, -19}, {111, 111, 159}, {112, 122, 34}, },
            {{101, 101, 160}, },
            {{115, 115, 161}, },
            {{97, 97, 162}, },
            {{45, 95, -9}, {97, 97, 163}, {98, 122, 34}, },
            {{45, 109, -41}, {110, 110, 164}, {111, 122, 34}, },
            {{45, 114, -59}, {115, 115, 165}, {116, 122, 34}, },
            {{45, 115, -40}, {116, 116, 166}, {117, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 99, -22}, {100, 100, 167}, {101, 122, 34}, },
            {{45, 100, -25}, {101, 101, 168}, {102, 122, 34}, },
            {{45, 100, -25}, {101, 101, 169}, {102, 122, 34}, },
            {{45, 109, -41}, {110, 110, 170}, {111, 122, 34}, },
            {{116, 116, 171}, },
            {{101, 101, 172}, },
            {{110, 110, 173}, },
            {{45, 107, -101}, {108, 108, 174}, {109, 122, 34}, },
            {{45, 95, -9}, {97, 97, 175}, {98, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 114, -59}, {115, 115, 176}, {116, 122, 34}, },
            {{45, 113, -21}, {114, 114, 177}, {115, 122, 34}, },
            {{45, 114, -59}, {115, 115, 178}, {116, 122, 34}, },
            {{45, 95, -9}, {97, 120, 34}, {121, 121, 179}, {122, 122, 34}, },
            {{45, 114, -59}, {115, 115, 180}, {116, 122, 34}, },
            {{62, 62, 181}, },
            {{116, 116, 182}, },
            {{116, 116, 183}, },
            {{45, 122, -9}, },
            {{45, 115, -40}, {116, 116, 184}, {117, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 100, -25}, {101, 101, 185}, {102, 122, 34}, },
            {{45, 114, -59}, {115, 115, 186}, {116, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 122, -9}, },
            {{62, 62, 187}, },
            {{62, 62, 188}, },
            {{62, 62, 189}, },
            {{45, 116, -17}, {117, 117, 190}, {118, 122, 34}, },
            {{45, 114, -59}, {115, 115, 191}, {116, 122, 34}, },
            {{45, 122, -9}, },
            {},
            {{62, 62, 192}, },
            {{62, 62, 193}, },
            {{45, 113, -21}, {114, 114, 194}, {115, 122, 34}, },
            {{45, 114, -59}, {115, 115, 195}, {116, 122, 34}, },
            {},
            {},
            {{45, 100, -25}, {101, 101, 196}, {102, 122, 34}, },
            {{45, 122, -9}, },
            {{45, 122, -9}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {27, 25, 25, 27, 2, 3, 0, 23, 23, 23, -1, 1, 23, -1, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 4, 5, 26, 23, 23, 23, 23, 23, 23, -1, -1, 24, 23, 23, 23, 23, 23, 9, 23, 23, 23, 23, 23, 23, -1, -1, -1, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, -1, -1, -1, 23, 23, 23, 16, 23, 23, 23, 23, 23, 23, 23, 23, -1, -1, -1, 23, 23, 23, 23, 20, 23, 23, 23, 23, 23, 23, -1, -1, -1, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, -1, -1, -1, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, -1, -1, -1, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, -1, -1, -1, 21, 19, 23, 23, 23, 23, 23, 23, 23, 23, 23, -1, -1, -1, 23, 23, 23, 23, 18, 23, 23, 23, 23, -1, -1, -1, 23, 23, 14, 23, 23, 23, 23, 23, -1, -1, -1, 22, 23, 15, 23, 23, 10, 13, -1, -1, -1, 23, 23, 11, 7, -1, -1, 23, 23, 8, 6, 23, 17, 12, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
