/* This file was generated by SableCC (http://www.sablecc.org/). */

package plantuml.parser;

import plantuml.node.*;
import plantuml.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 0;
    }

    @Override
    public void caseTArrow(@SuppressWarnings("unused") TArrow node)
    {
        this.index = 1;
    }

    @Override
    public void caseTLDAng(@SuppressWarnings("unused") TLDAng node)
    {
        this.index = 2;
    }

    @Override
    public void caseTRDAng(@SuppressWarnings("unused") TRDAng node)
    {
        this.index = 3;
    }

    @Override
    public void caseTNoteMsgAng(@SuppressWarnings("unused") TNoteMsgAng node)
    {
        this.index = 4;
    }

    @Override
    public void caseTMsgLink(@SuppressWarnings("unused") TMsgLink node)
    {
        this.index = 5;
    }

    @Override
    public void caseTQuot(@SuppressWarnings("unused") TQuot node)
    {
        this.index = 6;
    }

    @Override
    public void caseTSlash(@SuppressWarnings("unused") TSlash node)
    {
        this.index = 7;
    }

    @Override
    public void caseTStartdiagramTok(@SuppressWarnings("unused") TStartdiagramTok node)
    {
        this.index = 8;
    }

    @Override
    public void caseTEnddiagramTok(@SuppressWarnings("unused") TEnddiagramTok node)
    {
        this.index = 9;
    }

    @Override
    public void caseTParticipantTok(@SuppressWarnings("unused") TParticipantTok node)
    {
        this.index = 10;
    }

    @Override
    public void caseTStereotypeTok(@SuppressWarnings("unused") TStereotypeTok node)
    {
        this.index = 11;
    }

    @Override
    public void caseTAliasTok(@SuppressWarnings("unused") TAliasTok node)
    {
        this.index = 12;
    }

    @Override
    public void caseTNoteTok(@SuppressWarnings("unused") TNoteTok node)
    {
        this.index = 13;
    }

    @Override
    public void caseTLeftTok(@SuppressWarnings("unused") TLeftTok node)
    {
        this.index = 14;
    }

    @Override
    public void caseTRightTok(@SuppressWarnings("unused") TRightTok node)
    {
        this.index = 15;
    }

    @Override
    public void caseTOverTok(@SuppressWarnings("unused") TOverTok node)
    {
        this.index = 16;
    }

    @Override
    public void caseTEndTok(@SuppressWarnings("unused") TEndTok node)
    {
        this.index = 17;
    }

    @Override
    public void caseTCharSeq(@SuppressWarnings("unused") TCharSeq node)
    {
        this.index = 18;
    }

    @Override
    public void caseTOpaqueexpr(@SuppressWarnings("unused") TOpaqueexpr node)
    {
        this.index = 19;
    }

    @Override
    public void caseTNewLine(@SuppressWarnings("unused") TNewLine node)
    {
        this.index = 20;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 21;
    }
}
